name: Phase2 Issue
description: Phase2で着手するタスクの登録用テンプレート
title: "[Phase2] "
labels:
  - phase2
body:
  - type: markdown
    attributes:
      value: |
        Phase2のタスクを整理するためのテンプレートです。
  - type: input
    id: objective
    attributes:
      label: 目的
      description: このIssueで達成したいこと
      placeholder: 例) スクレイパーの収集対象を拡張する
    validations:
      required: true
  - type: textarea
    id: tasks
    attributes:
      label: 作業内容
      description: 実施する作業をチェックリストで記載
      placeholder: |
        - [ ] 仕様確認
        - [ ] 実装
        - [ ] テスト
    validations:
      required: true
  - type: textarea
    id: done_definition
    attributes:
      label: 完了条件
      description: このIssueが完了と判断できる条件
      placeholder: 例) 期待データが継続収集され、監視で異常が出ていない
    validations:
      required: true
  - type: input
    id: due
    attributes:
      label: 目標日
      description: 任意（YYYY-MM-DD）
      placeholder: 2026-04-15
    validations:
      required: false
