type Table<Row> = {
  Row: Row;
  Insert: Partial<Row>;
  Update: Partial<Row>;
  Relationships: [];
};

export type Team = {
  team_id: string;
  team_name_j: string;
  team_name_e: string | null;
  team_short_name_j: string | null;
  team_short_name_e: string | null;
  created_at: string;
  updated_at: string;
};

export type Game = {
  schedule_key: number;
  season: string;
  code: number;
  convention_key: string;
  convention_name_j: string;
  convention_name_e: string | null;
  year: number;
  setu: string | null;
  game_type: string | null;
  max_period: number;
  game_current_period: number | null;
  game_datetime_unix: number;
  game_datetime: string | null;
  game_date: string | null;
  stadium_cd: string | null;
  stadium_name_j: string | null;
  stadium_name_e: string | null;
  attendance: number | null;
  game_ended_flg: boolean;
  record_fixed_flg: boolean;
  boxscore_exists_flg: boolean;
  play_by_play_exists_flg: boolean;
  home_team_id: string;
  away_team_id: string;
  home_team_score_q1: number | null;
  home_team_score_q2: number | null;
  home_team_score_q3: number | null;
  home_team_score_q4: number | null;
  home_team_score_q5: number | null;
  home_team_score_total: number | null;
  away_team_score_q1: number | null;
  away_team_score_q2: number | null;
  away_team_score_q3: number | null;
  away_team_score_q4: number | null;
  away_team_score_q5: number | null;
  away_team_score_total: number | null;
  referee_id: number | null;
  referee_name_j: string | null;
  sub_referee_id_1: number | null;
  sub_referee_name_j_1: string | null;
  sub_referee_id_2: number | null;
  sub_referee_name_j_2: string | null;
  source_tab: number | null;
  scraped_at: string;
  updated_at: string;
};

export type GameTeamStats = {
  schedule_key: number;
  team_id: string;
  opponent_team_id: string | null;
  is_home: boolean;
  points: number | null;
  fgm: number | null;
  fga: number | null;
  fg_pct: number | null;
  fg2m: number | null;
  fg2a: number | null;
  fg2_pct: number | null;
  fg3m: number | null;
  fg3a: number | null;
  fg3_pct: number | null;
  ftm: number | null;
  fta: number | null;
  ft_pct: number | null;
  off_rebounds: number | null;
  def_rebounds: number | null;
  total_rebounds: number | null;
  assists: number | null;
  steals: number | null;
  blocks: number | null;
  blocks_received: number | null;
  turnovers: number | null;
  fouls: number | null;
  fouls_drawn: number | null;
  dunks: number | null;
  fast_break_points: number | null;
  second_chance_points: number | null;
  points_in_paint: number | null;
  possession: number | null;
  pace: number | null;
  off_rtg: number | null;
  def_rtg: number | null;
  net_rtg: number | null;
  ast_rtg: number | null;
  tov_rtg: number | null;
  pft_rtg: number | null;
  scp_rtg: number | null;
  efg_pct: number | null;
  ts_pct: number | null;
  ast_pct: number | null;
  tov_pct: number | null;
  ast_tov_ratio: number | null;
  play_pct: number | null;
  ft_d_pct: number | null;
  ft_freq: number | null;
  ft_rate: number | null;
  orb_pct: number | null;
  drb_pct: number | null;
  pft_pct: number | null;
  fbp_pct: number | null;
  scp_pct: number | null;
  pitp_pct: number | null;
  perimeter_pts_pct: number | null;
  pt2_attempt_pct: number | null;
  pt3_attempt_pct: number | null;
  pt2_points_share: number | null;
  pt3_points_share: number | null;
  ft_points_share: number | null;
  live_tov_pct: number | null;
  dead_tov_pct: number | null;
  live_tov_share: number | null;
  dead_tov_share: number | null;
  shot_chances: number | null;
  off_success_count: number | null;
  or_chances: number | null;
  dr_chances: number | null;
  tom: number | null;
  eff: number | null;
  vps: number | null;
  home_efg_pct: number | null;
  away_efg_pct: number | null;
  home_ts_pct: number | null;
  away_ts_pct: number | null;
  home_off_rtg: number | null;
  away_off_rtg: number | null;
  close_win_3pts_or_less: number | null;
  close_loss_3pts_or_less: number | null;
  pythagorean_win_pct: number | null;
  opp_possession: number | null;
  opp_efg_pct: number | null;
  opp_ts_pct: number | null;
  opp_fg2_pct: number | null;
  opp_fg3_pct: number | null;
  opp_pt2_attempt_pct: number | null;
  opp_pt3_attempt_pct: number | null;
  opp_pt2_points_share: number | null;
  opp_pt3_points_share: number | null;
  opp_ft_points_share: number | null;
  opp_ast_pct: number | null;
  opp_ast_tov_ratio: number | null;
  opp_ast_rtg: number | null;
  opp_tov_pct: number | null;
  opp_orb_pct: number | null;
  opp_drb_pct: number | null;
  opp_shot_chances: number | null;
  opp_success_count: number | null;
  opp_ft_d_pct: number | null;
  opp_ft_rate: number | null;
  opp_fbp_pct: number | null;
  opp_scp_pct: number | null;
  opp_scp_rtg: number | null;
  opp_pitp_pct: number | null;
  opp_perimeter_pts_pct: number | null;
  opp_pft_pct: number | null;
  opp_pft_rtg: number | null;
  opp_vps: number | null;
  home_opp_efg_pct: number | null;
  away_opp_efg_pct: number | null;
  home_opp_ts_pct: number | null;
  away_opp_ts_pct: number | null;
  created_at: string;
  updated_at: string;
};

export type Player = {
  player_id: string;
  player_name_j: string;
  player_name_e: string | null;
  last_seen_team_id: string | null;
  last_seen_jersey_number: string | null;
  player_slot_category: string | null;
  league_registered_nationality: string | null;
  birthplace: string | null;
  entity_type: 'player' | 'staff' | 'placeholder' | 'unresolved';
  created_at: string;
  updated_at: string;
};

export type PlayerGameStats = {
  schedule_key: number;
  player_id: string;
  team_id: string;
  jersey_number: string | null;
  is_starter: boolean;
  is_playing: boolean;
  play_time: string | null;
  points: number | null;
  fgm: number | null;
  fga: number | null;
  fg_pct: number | null;
  fg2m: number | null;
  fg2a: number | null;
  fg2_pct: number | null;
  fg3m: number | null;
  fg3a: number | null;
  fg3_pct: number | null;
  ftm: number | null;
  fta: number | null;
  ft_pct: number | null;
  off_rebounds: number | null;
  def_rebounds: number | null;
  total_rebounds: number | null;
  assists: number | null;
  turnovers: number | null;
  steals: number | null;
  blocks: number | null;
  blocks_received: number | null;
  fouls: number | null;
  fouls_drawn: number | null;
  fast_break_points: number | null;
  points_in_paint: number | null;
  second_chance_points: number | null;
  efficiency: number | null;
  plus_minus: number | null;
  ast_to_ratio: number | null;
  efg_pct: number | null;
  ts_pct: number | null;
  usg_pct: number | null;
  created_at: string;
  updated_at: string;
};

export type Database = {
  public: {
    Tables: {
      teams: Table<Team>;
      games: Table<Game>;
      game_team_stats: Table<GameTeamStats>;
      players: Table<Player>;
      player_game_stats: Table<PlayerGameStats>;
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
