-- Issue #25: backup and persistent reviewed player profile patch
-- Date: 2026-08-20
-- Source: supabase/patches/20260819_issue25_missing_player_profiles_proposed.csv
-- Scope: 281 players after Issue #25 ID consolidation.
-- Run first. This script does not update public.players.
-- Blank proposed nationality/birthplace values are intentionally ignored by fix.
-- player_slot_category is normalized to: 日本人選手 / 外国籍選手 / 帰化選手.

DO $issue_25_profile_backup$
DECLARE
    target_rows INTEGER;
    backup_rows INTEGER;
BEGIN
    IF TO_REGCLASS('public.data_patch_backup_20260820_issue25_player_profiles') IS NOT NULL
       OR TO_REGCLASS('public.data_patch_issue25_player_profiles') IS NOT NULL THEN
        RAISE EXCEPTION 'Issue #25 profile backup or patch table already exists; inspect before re-running';
    END IF;

    CREATE TABLE public.data_patch_backup_20260820_issue25_player_profiles AS
        SELECT p.* FROM public.players p WHERE FALSE;

    CREATE TABLE public.data_patch_issue25_player_profiles (
        player_id TEXT PRIMARY KEY,
        player_name_j TEXT NOT NULL,
        player_name_e TEXT,
        proposed_league_registered_nationality TEXT,
        proposed_birthplace TEXT,
        normalized_player_slot_category TEXT NOT NULL
    );

    INSERT INTO public.data_patch_issue25_player_profiles (
        player_id, player_name_j, player_name_e,
        proposed_league_registered_nationality, proposed_birthplace,
        normalized_player_slot_category
    ) VALUES
    ('10256', 'ドゥレイロン・バーンズ', 'Draelon Burns', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('10265', 'デクスター・ピットマン', 'Dexter Pittman', NULL, NULL, '外国籍選手'),
    ('10817', 'クレイグ・ブラッキンズ', 'Craig Brackins', NULL, NULL, '外国籍選手'),
    ('10819', 'ロバート・サクレ', 'Robert Sacre', NULL, NULL, '外国籍選手'),
    ('10823', 'イバン・ラベネル', 'Evan Ravenel', NULL, NULL, '外国籍選手'),
    ('10875', 'グレッグ・マンガーノ', 'Greg Mangano', NULL, NULL, '外国籍選手'),
    ('10886', 'ジェフ・エアーズ', 'Jeff Ayres', NULL, NULL, '外国籍選手'),
    ('10887', 'トレント・プレイステッド', 'Trent Plaisted', NULL, NULL, '外国籍選手'),
    ('10897', 'レオ・ライオンズ', 'Leo Lyons', NULL, NULL, '外国籍選手'),
    ('12457', 'トニー・ガフニー', 'Tony Gaffney', NULL, NULL, '外国籍選手'),
    ('12459', 'カディーム・コールビー', 'Kadeem Coleby', NULL, NULL, '外国籍選手'),
    ('12507', 'ジャスティン・レイノルズ', 'Justin Reynolds', NULL, NULL, '外国籍選手'),
    ('12508', 'ブランデン・ドーソン', 'Branden Dawson', NULL, NULL, '外国籍選手'),
    ('12523', 'カルティエ・マーティン', 'Cartier Martin', NULL, NULL, '外国籍選手'),
    ('12578', 'ランデン・ルーカス', 'Landen Lucas', NULL, NULL, '外国籍選手'),
    ('12579', 'ジャレッド・バーグレン', 'Jared Berggren', NULL, NULL, '外国籍選手'),
    ('12580', 'ジャワッド・ウィリアムズ', 'Jawad Williams', NULL, NULL, '外国籍選手'),
    ('12581', 'オースティン・ダフォー', 'Austin Dufault', NULL, NULL, '外国籍選手'),
    ('12583', 'デイビッド・ウェア', 'David Wear', NULL, NULL, '外国籍選手'),
    ('12584', 'グレッグ・スミス', 'Greg Smith', NULL, NULL, '外国籍選手'),
    ('12585', 'ディオール・フィッシャー', 'D''or Fischer', NULL, NULL, '外国籍選手'),
    ('12586', 'オマール・サムハン', 'Omar Samhan', NULL, NULL, '外国籍選手'),
    ('12591', 'バンバ ・ジュフ', 'Bamba Diouf', NULL, NULL, '帰化選手'),
    ('12594', 'グレゴリー・ウィッティントン', 'Gregory Whittington', NULL, NULL, '外国籍選手'),
    ('12595', 'マーク・トラソリーニ', 'Marc Trasolini', NULL, NULL, '外国籍選手'),
    ('12596', 'ハーバート・ヒル', 'Herbert Hill', NULL, NULL, '外国籍選手'),
    ('12630', 'ブレンダン・レーン', 'Brendan Lane', NULL, NULL, '外国籍選手'),
    ('12636', 'ダニエル・オルトン', 'Daniel Orton', NULL, NULL, '外国籍選手'),
    ('12637', 'ハンター・コート', 'Hunter Cort', NULL, NULL, '日本人選手'),
    ('12640', 'ハシーム・サビート・マンカ', 'Hasheem Thabeet Manka', NULL, NULL, '外国籍選手'),
    ('12642', 'アンジェロ・チョル', 'Angelo Chol', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('12648', 'ジョーダン・フェイゾン', 'Jordan Faison', NULL, NULL, '外国籍選手'),
    ('12660', 'ジージオ・ベイン', 'Gjio Bain', NULL, NULL, '外国籍選手'),
    ('12663', 'ウィリアム・マクドナルド', 'William Mcdonald', NULL, NULL, '外国籍選手'),
    ('15750', '木田 貴明', 'Takaaki Kida', '日本', '日本', '日本人選手'),
    ('15805', 'ルー・アマンドソン', 'Lou Amundson', NULL, NULL, '外国籍選手'),
    ('15809', 'ジャミール・マッケイ', 'Mckay Jameel', NULL, NULL, '外国籍選手'),
    ('15812', 'ベンキー・ジョイス', 'Venky Jois', NULL, NULL, '外国籍選手'),
    ('15814', 'キース・ベンソン', 'Keith Benson', NULL, NULL, '外国籍選手'),
    ('15845', 'ディジョン・トンプソン', 'Dijon Thompson', NULL, NULL, '外国籍選手'),
    ('15847', 'コートニー・シムズ', 'Courtney Sims', NULL, NULL, '外国籍選手'),
    ('15848', 'アル・ソーントン', 'Al Thornton', NULL, NULL, '外国籍選手'),
    ('15849', 'ダシルバ ヒサシ', 'Hisashi Da Silva', NULL, NULL, '日本人選手'),
    ('15852', 'ジャマリ・トレイラー', 'Jamari Traylor', NULL, NULL, '外国籍選手'),
    ('18168', 'アマンゼ・エゲケゼ', 'Amanze Egekeze', NULL, NULL, '外国籍選手'),
    ('18169', 'チャールズ・ガルシア', 'Charles García', NULL, NULL, '外国籍選手'),
    ('18171', '紺野 ニズベット 翔', 'Shou Nisbet', NULL, NULL, '日本人選手'),
    ('18173', 'ドゥワン・サマーズ', 'Dajuan Summers', NULL, NULL, '外国籍選手'),
    ('18397', 'ミルコ・ビエリツァ', 'Milko Bjelica', NULL, NULL, '外国籍選手'),
    ('18426', 'バーノン・マクリン', 'Vernon Macklin', NULL, NULL, '外国籍選手'),
    ('18427', 'シェーン・エドワーズ', 'Shane Edwards', NULL, NULL, '外国籍選手'),
    ('18431', 'ガニ・ラワル', 'Gani Lawal', NULL, NULL, '外国籍選手'),
    ('18432', 'グレゴリー・エチェニケ', 'Gregory Echenique', NULL, NULL, '外国籍選手'),
    ('18436', 'ジェームズ・サザランド', 'James Southerland', NULL, NULL, '外国籍選手'),
    ('18442', 'ベンジャミン・ローソン', 'Benjamin Lawson', NULL, NULL, '外国籍選手'),
    ('18444', 'シャキール・モリス', 'Shaquille Morris', NULL, NULL, '外国籍選手'),
    ('18452', 'エリック・ロバーツ', 'Eric Roberts', NULL, NULL, '日本人選手'),
    ('18459', 'ジャボン・マックレア', 'Javon Mccrea', NULL, NULL, '外国籍選手'),
    ('18473', 'プリンス・イベ', 'Prince Ibeh', NULL, NULL, '外国籍選手'),
    ('18479', 'ケネディ・ミークス', 'Kennedy Meeks', NULL, NULL, '外国籍選手'),
    ('18846', 'アーサー・スティーブンソン', 'Arthur Stepheson', NULL, NULL, '外国籍選手'),
    ('19955', 'ドワイト・コールビー', 'Dwight Coleby', NULL, NULL, '外国籍選手'),
    ('19958', 'バイロン・ミュレンズ', 'Byron Mullens', NULL, NULL, '外国籍選手'),
    ('19995', 'ブランドン・コストナー', 'brandon Costner', NULL, NULL, '外国籍選手'),
    ('19997', 'マーカス・ブレイクリー', 'Marqus Blakely', NULL, NULL, '外国籍選手'),
    ('20020', 'トレバー・ムバクウェ', 'Trevor Mbakwe', NULL, NULL, '外国籍選手'),
    ('20032', 'アラン・ハーンドン', 'Alan Herndon', NULL, NULL, '外国籍選手'),
    ('20033', 'セドリック・シモンズ', 'Cedric Simmons', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('22396', 'ジョナサン・ホームズ', 'Jonathan Holmes', NULL, NULL, '外国籍選手'),
    ('22400', 'ヘンリー・ウォーカー', 'Henry Walker', NULL, NULL, '外国籍選手'),
    ('22404', 'ダニエル・ジョンソン', 'Daniel Johnson', NULL, NULL, '外国籍選手'),
    ('22522', 'ペリー・エリス', 'Perry Ellis', NULL, NULL, '外国籍選手'),
    ('25136', 'エリック・ニッセン', 'Erik Nissen', NULL, NULL, '外国籍選手'),
    ('25149', 'イシュマエル・レーン', 'Ishmael Lane', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('26825', 'ロバート・カーター', 'Robert Carter', NULL, NULL, '外国籍選手'),
    ('26826', 'ブライアン・クウェリ', 'Brian Qvale', NULL, NULL, '外国籍選手'),
    ('26875', 'マティアス・カルファニ', 'Mathias Calfani', NULL, NULL, '外国籍選手'),
    ('26892', 'ミッケル・グラッドネス', 'Mickell Gladness', NULL, NULL, '外国籍選手'),
    ('26893', 'ジョルジー・ゴロマン', 'Gyorgy Galoman', NULL, NULL, '外国籍選手'),
    ('26897', 'デビン・イーバンクス', 'Devin Ebanks', NULL, NULL, '外国籍選手'),
    ('26898', 'ジェシー・ゴーバン', 'Jessie Govan', NULL, NULL, '外国籍選手'),
    ('26909', 'クリス・オトゥーレ', 'Chris Otule', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('26910', 'チャールズ・ローズ', 'Chales Rhodes', NULL, NULL, '外国籍選手'),
    ('26911', 'リチャード・ヘンドリックス', 'Richard Hendrix', NULL, NULL, '外国籍選手'),
    ('26915', 'レジナルド・ベクトン', 'Reginald Becton', NULL, NULL, '外国籍選手'),
    ('26916', 'ミラン・マチュワン', 'Milan Macvan', NULL, NULL, '外国籍選手'),
    ('26928', 'マーク・セントフォート', 'Mark Saint Fort', NULL, NULL, '外国籍選手'),
    ('26931', 'シャブリック・ランドルフ', 'Shavlik Randolph', NULL, NULL, '外国籍選手'),
    ('26938', 'ラシャーン・ホロウェイ', 'Rashaan Holloway', NULL, NULL, '外国籍選手'),
    ('27051', 'ユージーン・フェルプス', 'Eugene Phelps', NULL, NULL, '外国籍選手'),
    ('30393', 'ヴィアチェスラフ・クラフツォフ', 'Viacheslav Kravtsov', NULL, NULL, '外国籍選手'),
    ('30435', 'クリス・ジョンソン', 'Chris Johnson', NULL, NULL, '外国籍選手'),
    ('32952', 'パブロ・アギラール', 'Pablo Aguilar', NULL, NULL, '外国籍選手'),
    ('32981', 'ステヴァン・イェロヴァツ', 'Stevan Jelovac', NULL, NULL, '外国籍選手'),
    ('32983', '駒水 大雅ジャック', 'Taiga Jack Komamizu', NULL, NULL, '日本人選手'),
    ('32990', 'シャノン・ショーター', 'Shannon Shorter', NULL, NULL, '外国籍選手'),
    ('32994', 'ジョーダン・テイラー', 'Jordan Taylor', NULL, NULL, '外国籍選手'),
    ('33030', 'ネナド・ミリェノヴィッチ', 'Nenad Miljenovic', NULL, NULL, '外国籍選手'),
    ('33031', 'レイヴォンテ・ライス', 'Rayvonte Rice', NULL, NULL, '外国籍選手'),
    ('33037', 'ジョナサン・オクテウス', 'Jonathan Octeus', NULL, NULL, '外国籍選手'),
    ('33042', 'デクアン・ジョーンズ', 'DeQuan Jones', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('33045', 'アレックス・デイビス', 'Alex Davis', NULL, NULL, '外国籍選手'),
    ('33093', 'シェーン・ウィティングトン', 'Shayne Whittington', NULL, NULL, '外国籍選手'),
    ('33096', 'キム・ティリ', 'Kim Tillie', NULL, NULL, '外国籍選手'),
    ('33098', 'リチャード・ソロモン', 'Richard Solomon', NULL, NULL, '外国籍選手'),
    ('40153', 'ダニエル・ギデンズ', 'Daniel Giddens', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('43470', '加賀谷 ジェームス 洸太朗', 'Kotaro James kagaya', 'ユース育成特別枠', '鹿児島県', '日本人選手'),
    ('45866', '角田 太輝', 'Taiki Sumida', NULL, '日本', '日本人選手'),
    ('45867', '湧川 颯斗', 'Hayato Wakugawa', NULL, '日本', '日本人選手'),
    ('45868', '佐土原 遼', 'Ryo Sadohara', NULL, '日本', '日本人選手'),
    ('45869', '八村 阿蓮', 'Allen Hachimura', NULL, '日本', '日本人選手'),
    ('45870', '渡邉 飛勇', 'Hugh Watanabe', NULL, '日本', '日本人選手'),
    ('45871', '川真田 紘也', 'Koya Kawamata', NULL, '日本', '日本人選手'),
    ('5100000003', 'デション・トーマス', 'Deshaun Thomas', NULL, NULL, '外国籍選手'),
    ('5100000007', 'ジョーダン・グリン', 'Jordan Glynn', NULL, NULL, '外国籍選手'),
    ('5100000047', 'コルトン・アイバーソン', 'Colton Iverson', NULL, NULL, '外国籍選手'),
    ('5100000060', 'レイトン・ハモンズ', 'Leyton Hammonds', NULL, NULL, '外国籍選手'),
    ('5100000061', 'オヴィ・ソコ', 'Ovie Soko', NULL, NULL, '外国籍選手'),
    ('5100000064', '青木 龍史', 'Ryuji Aoki', NULL, '日本', '日本人選手'),
    ('5100000065', 'オンドレイ・バルヴィン', 'Ondrej Balvin', NULL, NULL, '外国籍選手'),
    ('5100000067', 'ジャスティン・ノックス', 'Justin Knox', NULL, NULL, '外国籍選手'),
    ('5100000068', 'エリアス・ハリス', 'Elias Harris', NULL, NULL, '外国籍選手'),
    ('5100000072', 'マイケル・クレイグ', 'Michael Craig', NULL, NULL, '外国籍選手'),
    ('5100000086', 'ハビエル・ゴメス デ リアニョ', 'Javier Gomez de Liano', NULL, NULL, '外国籍選手'),
    ('5100000090', 'マーク・バートン', 'Mark Burton', '日本', '日本', '日本人選手'),
    ('51000098', 'ジェイコブス 晶', 'Akira Jacobs', NULL, NULL, '日本人選手'),
    ('51000106', 'ロバート・ドジャー', 'Robert Dozier', NULL, NULL, '日本人選手'),
    ('51000114', '寺澤 大夢', 'Hiromu Terasawa', NULL, '日本', '日本人選手'),
    ('51000126', 'ピータージュニア・オコエ', 'Peter Junior Okoye', NULL, NULL, '外国籍選手'),
    ('51000131', 'デュサン・ヴィチェンティッチ', 'Dusan Vicentic', NULL, NULL, '外国籍選手'),
    ('51000161', 'ジェイコブ・ワイリー', 'Jacob Wiley', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('51000189', 'ブランドン・アシュリー', 'Brandon Ashley', 'アメリカ合衆国', 'アメリカ合衆国', '外国籍選手'),
    ('51000218', 'アンドリュー・ファーガソン', 'Andrew Ferguson', NULL, 'オーストラリア', '外国籍選手'),
    ('51000219', 'ウィリアム・モズリー', 'William Mosley', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('51000225', '平岡 勇人', 'Yuto Hiraoka', NULL, '日本', '日本人選手'),
    ('51000226', 'エペ・ウドゥ', 'Ekpe Udoh', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('51000229', 'キャメロン・クラットウィグ', 'Cameron Krutwig', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('51000241', 'シズ・オルストン', 'Shizz Alston', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('51000261', 'パク ジェヒョン', 'Jaehyun Park', NULL, '大韓民国', '外国籍選手'),
    ('51000262', 'サムソン・フローリング', 'Samson Froling', NULL, 'オーストラリア', '外国籍選手'),
    ('51000334', 'ジョニー・オブライアント', 'Johnny O''Bryant', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('51000340', '井手 歩由夢', 'Ayumu Ide', NULL, '日本', '日本人選手'),
    ('51000369', '橋谷 真季', 'Manaki Hashiya', NULL, '日本', '日本人選手'),
    ('51000426', 'ミッチェル・ライトフット', 'Mitchell Lightfoot', 'アメリカ合衆国', 'アメリカ合衆国', '外国籍選手'),
    ('51000427', 'タイラー・ラム', 'Tyler Lamb', NULL, NULL, '外国籍選手'),
    ('51000490', 'ブランドン・デイヴィス', 'Brandon Davies', 'アメリカ合衆国', 'アメリカ合衆国', '外国籍選手'),
    ('51000497', 'ディディ・ロウザダ', 'Didi Louzada', 'ブラジル', 'ブラジル', '外国籍選手'),
    ('51000511', 'セクー・ドゥムブヤ', 'Sekou Doumbouya', 'フランス', 'ギニア', '外国籍選手'),
    ('51000525', 'ジェイミー・マロンゾ', 'Jamie Malonzo', 'フィリピン', 'アメリカ合衆国', '外国籍選手'),
    ('51000533', 'デイボン・リード', 'Davon Reed', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('51000540', 'ティム・シュナイダー', 'Tim Schneider', 'ドイツ', 'ドイツ', '外国籍選手'),
    ('51000550', '松村 竜吾', 'Ryugo Matsumura', '日本', '日本', '日本人選手'),
    ('51000560', 'フランク・カミンスキー', 'FRANK KAMINSKY', 'アメリカ合衆国', 'アメリカ合衆国', '外国籍選手'),
    ('51000592', '針間 大知', 'Daichi Harima', '日本', '日本', '日本人選手'),
    ('51000593', '月岡 熙', 'Hikaru Tsukioka', '日本', '日本', '日本人選手'),
    ('51000599', '堀田 尚秀', 'Naohide Hotta', '日本', '日本', '日本人選手'),
    ('51000600', '岩屋 頼', 'Yori Iwaya', '日本', '日本', '日本人選手'),
    ('51000601', 'ギャリソン・ブルックス', 'Garrison Brooks', 'アメリカ合衆国', 'アメリカ合衆国', '外国籍選手'),
    ('51000603', '新井 翔太', 'Shota Arai', '日本', '日本', '日本人選手'),
    ('51000604', '武富 楓太', 'Futa Takedomi', '日本', '日本', '日本人選手'),
    ('51000605', '佐藤 瑠一シャンドレイ', 'Louieseandrey Sato', '日本', '日本', '日本人選手'),
    ('52433', 'ジョーダン・ナタイ', 'Jordan Ngatai', NULL, 'ニュージーランド', '外国籍選手'),
    ('55000009', '根本 晃', 'Ko Nemoto', NULL, '日本', '日本人選手'),
    ('55000015', '山田 悠斗', 'Yuto Yamada', NULL, '日本', '日本人選手'),
    ('55000067', '五明 一真', 'Kazuma Gomyo', NULL, '日本', '日本人選手'),
    ('55000076', '須藤 春輝', 'Haruki Sudo', NULL, '日本', '日本人選手'),
    ('55000077', '宜保 隼弥', 'shunya Gibo', NULL, '日本', '日本人選手'),
    ('55000174', '松下 湊人', 'Minato Matsushita', NULL, '日本', '日本人選手'),
    ('55000219', '南 拓摩', 'Takuma Minami', NULL, '日本', '日本人選手'),
    ('55000308', '菅野　楓太', 'Futa Sugano', NULL, '日本', '日本人選手'),
    ('55000363', '李 子浩', 'Kohiro Lee', NULL, '日本', '日本人選手'),
    ('55000423', '中西 真那斗', 'Manato Nakanishi', NULL, '日本', '日本人選手'),
    ('55000424', '佐藤 遼乙', 'Haruto Sato', NULL, '日本', '日本人選手'),
    ('55000450', '藤井 暖', 'Non Fujii', NULL, '日本', '日本人選手'),
    ('55000453', '小倉 貴志', 'Takashi Ogura', NULL, '日本', '日本人選手'),
    ('55000463', '中田 直斗', 'Naoto Nakata', NULL, '日本', '日本人選手'),
    ('55000510', '木戸 龍斗', 'Ryuto Kido', NULL, '日本', '日本人選手'),
    ('55000565', '稲葉 耕佑', 'Kosuke Inaba', NULL, '日本', '日本人選手'),
    ('55000566', '藤原 拓海', 'Takumi Fujiwara', NULL, '日本', '日本人選手'),
    ('55000569', '木山 大輔', 'Daisuke Kiyama', NULL, '日本', '日本人選手'),
    ('55000570', '山本 奨', 'Masashi Yamamoto', NULL, '日本', '日本人選手'),
    ('55000571', '松尾 和', 'Yamato Matsuo', NULL, '日本', '日本人選手'),
    ('55000572', '藤井 大', 'Yamato Fujii', NULL, '日本', '日本人選手'),
    ('55000574', '山﨑 成隆', 'Naritaka Yamazaki', '日本', '日本', '日本人選手'),
    ('55000576', '倉光 晴', 'Haru Kuramitsu', NULL, '日本', '日本人選手'),
    ('55000752', '服部 怜恩', 'Reon Hattori', NULL, '日本', '日本人選手'),
    ('55000811', '西田 瑛久', 'Eku Nishida', NULL, '日本', '日本人選手'),
    ('55000818', '井伊 拓海', 'Takuni Ii', NULL, '日本', '日本人選手'),
    ('55000826', '大越 海藍', 'Kai Ogoshi', NULL, '日本', '日本人選手'),
    ('55000845', '林 空翔', 'Takato Hayashi', NULL, '日本', '日本人選手'),
    ('55000868', '梅原 咲弥', 'Sakuya Umehara', NULL, '日本', '日本人選手'),
    ('55000960', '原田 ジョルジオ', 'Giorgio Harada', '日本', '日本', '日本人選手'),
    ('55000961', '栗原 琉空', 'Riku Kurihara', NULL, '日本', '日本人選手'),
    ('55000963', '長嶺 充来', 'Mirai Nagamine', NULL, '日本', '日本人選手'),
    ('55000964', '石原 蔵之助', 'Kuranosuke Ishihara', NULL, '日本', '日本人選手'),
    ('55000973', '高橋 秀成', 'Shusei Takahashi', NULL, '日本', '日本人選手'),
    ('55000974', '小松 亮太', 'Ryota Komatsu', NULL, '日本', '日本人選手'),
    ('55000975', '三上 寛太', 'Kanta Mikami', NULL, '日本', '日本人選手'),
    ('55000976', 'エルマスリ アダム', 'Adam Elmasri', '日本', '日本', '日本人選手'),
    ('55000977', '宮里 俊佑', 'Syunsuke Miyazato', NULL, '日本', '日本人選手'),
    ('55000978', '福地 勇太', 'Yudai Fukuchi', NULL, '日本', '日本人選手'),
    ('55000979', '川邉 蒼侑', 'Ayuki Kawabe', NULL, '日本', '日本人選手'),
    ('55000980', '中川 恵太', 'Keita Nakagawa', NULL, '日本', '日本人選手'),
    ('55000981', 'プラット 聖也', 'Sena Platt', '日本', '日本', '日本人選手'),
    ('8469', '菅澤 紀行', 'Noriyuki Sugasawa', NULL, '日本', '日本人選手'),
    ('8491', 'ジュフ 磨々道', 'Diouf Mamadou', NULL, NULL, '帰化選手'),
    ('8502', 'サム・ウィラード', 'Sam Willard', NULL, NULL, '外国籍選手'),
    ('8596', '桜木 ジェイアール', 'JR Sakuragi', NULL, '日本', '日本人選手'),
    ('8664', 'ドリュー・ヴァイニー', 'Drew Viney', NULL, NULL, '外国籍選手'),
    ('8689', '木下 博之', 'Hiroyuki Kinoshita', NULL, '日本', '日本人選手'),
    ('8723', '坂本　ジェイ', 'Dieye Sakamoto', NULL, NULL, '帰化選手'),
    ('8758', '澤地　サミュエルJr.', 'Sawaji Samuel Jr.', NULL, NULL, '日本人選手'),
    ('8760', 'ディショーン・スティーブンス', 'Deshawn Stephens', NULL, NULL, '外国籍選手'),
    ('8762', 'ケビン・コッツァー', 'Kevin Kotzur', NULL, NULL, '外国籍選手'),
    ('8834', 'トミー・ブレントン', 'Tommy Brenton', NULL, NULL, '外国籍選手'),
    ('8835', 'ジェフ・ギブス', 'Jeff Gibbs', NULL, 'アメリカ合衆国', '帰化選手'),
    ('8836', '山本 エドワード', 'Edward Yamamoto', NULL, NULL, '日本人選手'),
    ('8844', 'ジョシュ・デービス', 'Josh Davis', NULL, NULL, '外国籍選手'),
    ('9026', 'デイビット・ウィーバー', 'David Weaver', NULL, NULL, '外国籍選手'),
    ('9027', 'セオン・エディ', 'Seaun Eddy', NULL, NULL, '日本人選手'),
    ('9028', 'ディアンテ・ギャレット', 'Diante Garrett', NULL, NULL, '外国籍選手'),
    ('9030', '二ノ宮 康平', 'Kohei Ninomiya', NULL, NULL, '日本人選手'),
    ('9035', 'アンドリュー・ネイミック', 'Andrew　Naymick', NULL, NULL, '外国籍選手'),
    ('9038', 'トロイ・ギレンウォーター', 'Troy Gillenwater', NULL, NULL, '外国籍選手'),
    ('9041', 'クリント・チャップマン', 'Clint Chapman', NULL, NULL, '外国籍選手'),
    ('9042', 'スティーブン・バン・トリース', 'Stephan Van Treese', NULL, NULL, '外国籍選手'),
    ('9056', 'ヒルトン・アームストロング', 'Hilton Armstrong', NULL, NULL, '外国籍選手'),
    ('9057', 'タイラー・ストーン', 'Tyler Stone', NULL, NULL, '外国籍選手'),
    ('9058', 'スコット・モリソン', 'Scott Morrison', NULL, NULL, '外国籍選手'),
    ('9059', 'ケビン・パルマー', 'Kevin Palmer', NULL, NULL, '外国籍選手'),
    ('9062', 'エグゼビア・ギブソン', 'Xavier Gibson', NULL, NULL, '外国籍選手'),
    ('9071', 'ウィル・クリークモア', 'Will Creekmore', NULL, NULL, '帰化選手'),
    ('9081', 'カディーム・ジャック', 'Kadeem Jack', NULL, NULL, '外国籍選手'),
    ('9082', 'アールティー・グイン', 'R.T. Guinn', NULL, NULL, '外国籍選手'),
    ('9089', 'コナー・ラマート', 'Connor Lammert', NULL, NULL, '外国籍選手'),
    ('9090', 'キャメロン・リドリー', 'Cameron Ridley', NULL, NULL, '外国籍選手'),
    ('9266', 'ジーノ・ポマーレ', 'Gyno Pomare', NULL, NULL, '外国籍選手'),
    ('9316', 'ジョシュ・ペッパーズ', 'Josh Peppers', NULL, NULL, '外国籍選手'),
    ('9331', 'セドリック・ボーズマン', 'Cedric Bozeman', NULL, NULL, '外国籍選手'),
    ('9334', 'ライアン・スパングラー', 'Ryan Spangler', NULL, NULL, '外国籍選手'),
    ('9354', 'ロバート・ドジャー', 'Robert Dozier', NULL, NULL, '外国籍選手'),
    ('9355', 'オルー・アシャオル', 'Olu Ashaolu', NULL, NULL, '外国籍選手'),
    ('9356', 'リチャード・ロビー', 'Richard Roby', NULL, NULL, '外国籍選手'),
    ('9359', 'ローレンス・ヒル', 'Lawrence Hill', NULL, NULL, '外国籍選手'),
    ('9360', 'マーカス・ダブ', 'Marcus Dove', NULL, NULL, '外国籍選手'),
    ('9370', 'ディオン・ライト', 'Dion Wright', NULL, NULL, '外国籍選手'),
    ('9372', 'マーカリ・サンダース・フリソン', 'Markhuri Sanders Frison', NULL, NULL, '外国籍選手'),
    ('9379', 'カイル・バローン', 'Kyle Barone', NULL, NULL, '外国籍選手'),
    ('9381', 'ジョーダン・バチンスキー', 'Jordan Bachynski', NULL, NULL, '外国籍選手'),
    ('9382', 'ジェロウム・ティルマン', 'Jerome Tillman', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('9384', 'ラモント・ハミルトン', 'Lamont Hamilton', NULL, NULL, '外国籍選手'),
    ('9385', 'モー・チャーロ', 'Mo Charlo', NULL, NULL, '外国籍選手'),
    ('9391', 'アール・バロン', 'Earl Barron', NULL, NULL, '外国籍選手'),
    ('9392', 'ダニエル・ミラー', 'Daniel Miller', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('9393', 'ブライアン・フィッツパトリック', 'Brian　Fitzpatrick', NULL, NULL, '外国籍選手'),
    ('9400', 'ファイ パプ月瑠', 'PapeMour Faye', NULL, NULL, '帰化選手'),
    ('9403', 'ジェイソン・ウォッシュバーン', 'Jason Washburn', NULL, NULL, '外国籍選手'),
    ('9404', 'チャド・ポスチュマス', 'Chad　Posthumus', NULL, NULL, '外国籍選手'),
    ('9407', '高橋　マイケル', 'Michael Takahashi', NULL, NULL, '日本人選手'),
    ('9426', 'ルーベン・ボイキン', 'Ruben Boykin', NULL, NULL, '外国籍選手'),
    ('9431', 'ジョシュア・クロフォード', 'Joshua Crawford', NULL, 'アメリカ合衆国', '外国籍選手'),
    ('9448', 'アンドレ・マレー', 'Murray Andre', NULL, NULL, '外国籍選手'),
    ('9460', 'ジョーダン・ヴァンデンバーグ', 'Jordan Vandenberg', NULL, NULL, '外国籍選手'),
    ('9461', 'エンジェル・ガルシア', 'Angel Garcia', NULL, NULL, '外国籍選手'),
    ('9474', 'PARK JAE HAN', 'PARK JAE HAN', '韓国', '韓国', '外国籍選手'),
    ('9476', 'HAN HUI WON', 'HAN HUI WON', '韓国', '韓国', '外国籍選手'),
    ('9477', 'KIM JONG KEUN', 'KIM JONG KEUN', '韓国', '韓国', '外国籍選手'),
    ('9478', 'KIM MIN WOOK', 'KIM MIN WOOK', '韓国', '韓国', '外国籍選手'),
    ('9479', 'JEON SEONG HYEN', 'JEON SEONG HYEN', '韓国', '韓国', '外国籍選手'),
    ('9480', 'KEIFER J SYKES', 'KEIFER J SYKES', '韓国', '韓国', '外国籍選手'),
    ('9481', 'KIM CHEOL UK', 'KIM CHEOL UK', '韓国', '韓国', '外国籍選手'),
    ('9482', 'DAVID JOSEPH SIMON', 'DAVID JOSEPH SIMON', '韓国', '韓国', '外国籍選手'),
    ('9483', 'LEE JUNG HYUN', 'LEE JUNG HYUN', '韓国', '韓国', '外国籍選手'),
    ('9484', 'MOON SEONG GON', 'MOON SEONG GON', '韓国', '韓国', '外国籍選手'),
    ('9485', 'YANG HEE JONG', 'YANG HEE JONG', '韓国', '韓国', '外国籍選手'),
    ('9486', 'OH SE KEUN', 'OH SE KEUN', '韓国', '韓国', '外国籍選手'),
    ('9487', 'ローレンス・ブラックレッジ', 'Lawrence Blackledge', NULL, NULL, '外国籍選手'),
    ('9488', 'ジャマール・ソープ', 'Jahmar Thorpe', NULL, NULL, '外国籍選手'),
    ('9490', 'レイショーン・テリー', 'Reyshawn Terry', NULL, NULL, '外国籍選手'),
    ('9494', 'ウェンデル・ホワイト', 'Wendell White', NULL, NULL, '外国籍選手'),
    ('9495', 'ジョシュ・チルドレス', 'Josh Childress', NULL, NULL, '外国籍選手');

    SELECT COUNT(*) INTO target_rows
      FROM public.players p
      JOIN public.data_patch_issue25_player_profiles patch USING (player_id);
    IF target_rows <> 281 THEN
        RAISE EXCEPTION 'target row count mismatch: expected=281 actual=%', target_rows;
    END IF;

    INSERT INTO public.data_patch_backup_20260820_issue25_player_profiles
        SELECT p.*
          FROM public.players p
          JOIN public.data_patch_issue25_player_profiles patch USING (player_id);

    SELECT COUNT(*) INTO backup_rows
      FROM public.data_patch_backup_20260820_issue25_player_profiles;
    IF backup_rows <> 281 THEN
        RAISE EXCEPTION 'backup row count mismatch: expected=281 actual=%', backup_rows;
    END IF;

    REVOKE ALL ON TABLE public.data_patch_backup_20260820_issue25_player_profiles,
        public.data_patch_issue25_player_profiles FROM anon, authenticated;
END;
$issue_25_profile_backup$;

SELECT 'player_profiles' AS backup_scope,
       COUNT(*) AS row_count
  FROM public.data_patch_backup_20260820_issue25_player_profiles;
SELECT 'player_profile_patch' AS patch_scope,
       COUNT(*) AS row_count
  FROM public.data_patch_issue25_player_profiles;
